name: Terraform Deployment with Color

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (with color)
        run: |
          echo -e "\e[34mInitializing Terraform...\e[0m" # Blue color
          terraform init

      - name: Terraform Plan (with color)
        run: |
          echo -e "\e[33mGenerating Terraform Plan...\e[0m" # Yellow color
          terraform plan

      - name: Terraform Apply (with color)
        if: github.event_name == 'push'
        run: |
          echo -e "\e[32mApplying Terraform Configuration...\e[0m" # Green color
          terraform apply -auto-approve

      - name: Terraform Destroy (if needed)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged
        run: |
          echo -e "\e[31mDestroying Terraform Resources (PR Merged)...\e[0m" # Red color
          terraform destroy -auto-approve
