name: Terraform Deployment

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan with Colored Output
      run: |
        terraform plan -no-color | awk '
          /^\s*\+/ {print "\033[0;32m" $0 "\033[0m"; next}  # Green for create
          /^\s*-/  {print "\033[0;31m" $0 "\033[0m"; next}  # Red for delete
          /^\s*~/  {print "\033[0;33m" $0 "\033[0m"; next}  # Yellow for update
          {print}
        '
        
    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
