name: Terraform Deployment with Color

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (with color)
        run: |
          printf "\033[1;34m Initializing Terraform...\033[0m\n"
          terraform init -no-color

      - name: Terraform Plan (with color)
        run: |
          printf "\033[1;33m Running Terraform Plan...\033[0m\n"
          terraform plan -no-color -out=tfplan.out | awk '
            /^\s*\+/ {print "\033[0;32m" $0 "\033[0m"; next}
            /^\s*-/  {print "\033[0;31m" $0 "\033[0m"; next}
            /^\s*~/  {print "\033[0;33m" $0 "\033[0m"; next}
            {print}
          '

      - name: Terraform Apply (with color)
        if: github.event_name == 'push'
        run: |
          printf "\033[1;32m Applying Terraform Changes...\033[0m\n"
          terraform apply -no-color -auto-approve tfplan.out | awk '
            /^\s*\+/ {print "\033[0;32m" $0 "\033[0m"; next}
            /^\s*-/  {print "\033[0;31m" $0 "\033[0m"; next}
            /^\s*~/  {print "\033[0;33m" $0 "\033[0m"; next}
            {print}
          '

      - name: Terraform Destroy (on PR Merge)
        if: github.event.pull_request.merged == true
        run: |
          printf "\033[1;31m Destroying Terraform Resources...\033[0m\n"
          terraform destroy -no-color -auto-approve | awk '
            /^\s*\+/ {print "\033[0;32m" $0 "\033[0m"; next}
            /^\s*-/  {print "\033[0;31m" $0 "\033[0m"; next}
            /^\s*~/  {print "\033[0;33m" $0 "\033[0m"; next}
            {print}
          '
